<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ac8cd4c2-09ff-4f5a-b361-0679cb645965</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Pages\Report\ReportPage7.razor" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\**\*.resx">
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Blazor" Version="24.2.3" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Users\Shawn\source\repos\CommonLibrary\CommonLibrary\CommonLibrary.csproj" />
    <ProjectReference Include="..\..\Users\Shawn\source\repos\CommonLibrary\RazorCommonLibrary\RazorCommonLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Pages\Report\ReportPage5.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
</Project>